
export const PACKAGES = {
  1: { "name": "Swiss German", "id": 1, "continent": "EUROPE" },
  2: { "name": "Swiss French", "id": 2, "continent": "EUROPE" },
  3: { "name": "Swiss Italian", "id": 3, "continent": "EUROPE" },
  4: { "name": "Germany", "id": 4, "continent": "EUROPE" },
  5: { "name": "Italy", "id": 5, "continent": "EUROPE" },
  7: { "name": "Austria", "id": 7, "continent": "EUROPE" },
  //  8: { "name": "Belgium French", "id": 8, "continent": "EUROPE" },
  9: { "name": "France", "id": 9, "continent": "EUROPE" },
  10: { "name": "Spain", "id": 10, "continent": "EUROPE" },
  11: { "name": "England", "id": 11, "continent": "EUROPE" },
  12: { "name": "Wales", "id": 12, "continent": "EUROPE" },
  13: { "name": "Scotland", "id": 13, "continent": "EUROPE" },
  14: { "name": "Nortern Ireland", "id": 14, "continent": "EUROPE" },
  15: { "name": "Republic of Ireland", "id": 15, "continent": "EUROPE" },
  16: { "name": "Italy - North", "id": 16, "continent": "EUROPE" },
  17: { "name": "Italy - Center", "id": 17, "continent": "EUROPE" },
  18: { "name": "Italy - South", "id": 18, "continent": "EUROPE" },
  19: { "name": "Italy - Islands", "id": 19, "continent": "EUROPE" },
  //  20: { "name": "Australia", "id": 20, "continent": "EUROPE" },
  //  21: { "name": "India - English", "id": 21, "continent": "ASIA" },
  //  22: { "name": "New Zealand", "id": 22, "continent": "ASIA" },
  23: { "name": "Argentina", "id": 23, "continent": "SOUTH_AMERICA" },
  24: { "name": "Bolivia", "id": 24, "continent": "SOUTH_AMERICA" },
  25: { "name": "Chile", "id": 25, "continent": "SOUTH_AMERICA" },
  26: { "name": "Colombia", "id": 26, "continent": "SOUTH_AMERICA" },
  27: { "name": "Costa Rica", "id": 27, "continent": "SOUTH_AMERICA" },
  28: { "name": "Cuba", "id": 28, "continent": "SOUTH_AMERICA" },
  29: { "name": "Ecuador", "id": 29, "continent": "SOUTH_AMERICA" },
  30: { "name": "El Salvador", "id": 30, "continent": "SOUTH_AMERICA" },
  31: { "name": "Guatemala", "id": 31, "continent": "SOUTH_AMERICA" },
  32: { "name": "Honduras", "id": 32, "continent": "SOUTH_AMERICA" },
  33: { "name": "Mexico", "id": 33, "continent": "SOUTH_AMERICA" },
  34: { "name": "Nicaragua", "id": 34, "continent": "SOUTH_AMERICA" },
  35: { "name": "Paraguay", "id": 35, "continent": "SOUTH_AMERICA" },
  36: { "name": "Perú", "id": 36, "continent": "SOUTH_AMERICA" },
  37: { "name": "Uruguay", "id": 37, "continent": "SOUTH_AMERICA" },
  38: { "name": "Panamá", "id": 38, "continent": "SOUTH_AMERICA" },
  39: { "name": "Venezuela", "id": 39, "continent": "SOUTH_AMERICA" },
  40: { "name": "República Dominicana", "id": 40, "continent": "SOUTH_AMERICA" },
  //41: { "name": "United Arab Emirates (EN)", "id": 41, "continent": "AFRICA" },
  42: { "name": "USA", "id": 42, "continent": "NORTH_AMERICA" },
  43: { "name": "USA - Northeast", "id": 43, "continent": "NORTH_AMERICA" },
  44: { "name": "USA - Atlantic", "id": 44, "continent": "NORTH_AMERICA" },
  45: { "name": "USA - Southeast", "id": 45, "continent": "NORTH_AMERICA" },
  46: { "name": "USA - Central", "id": 46, "continent": "NORTH_AMERICA" },
  47: { "name": "USA - Northwest", "id": 47, "continent": "NORTH_AMERICA" },
  48: { "name": "USA - Pacific", "id": 48, "continent": "NORTH_AMERICA" },
  //49: { "name": "Pakistan", "id": 49, "continent": "NORTH_AMERICA" },
  //50: { "name": "Canada (EN)", "id": 50, "continent": "NORTH_AMERICA" },
  //51: { "name": "Canada (FR)", "id": 51, "continent": "NORTH_AMERICA" },
  //52: { "name": "Canada - Atlantic (EN)", "id": 52, "continent": "NORTH_AMERICA" },
  //53: { "name": "Canada - Central (EN)", "id": 53, "continent": "NORTH_AMERICA" },
  //54: { "name": "Canada - Pacific (EN)", "id": 54, "continent": "NORTH_AMERICA" },
  //55: { "name": "Canada - Quebec (FR)", "id": 55, "continent": "NORTH_AMERICA" },
  //56: { "name": "Canada - Ontario (FR)", "id": 56, "continent": "NORTH_AMERICA" },
  //57: { "name": "Canada - Brunswick (FR)", "id": 57, "continent": "NORTH_AMERICA" },
};
